footer: 'My footer | www.mywebsite.com'
header: 'My header | www.mywebsite.com'
style: ''
#theme: 'moon'
#theme: 'beige'
#theme: 'black' 
#theme: 'blood'
#theme: 'league'
#theme: 'night'
#theme: 'serif'
#theme: 'simple'
theme: 'sky'
#theme: 'solarized'
#theme: 'white.css'
